#import "template.typ": course

= Sport Studies, Society, Education and Olympic Studies
#course(name: [Introduction to Sport and Physical Education], id: [XS041011], semester: [2023–2024, Semester 1], credit: [2], ects: [3], hours: [32], content: [- Historical evolution of sport in China and the West - Concepts and functions of sport - Sport systems, school sport, competitive sport and social sport - Sport industry - Development of the Olympic Movement and its relationship with China], description: [This course interprets sport from historical, theoretical, comparative and international perspectives. It examines sport systems, different sectors of sport, the sport industry and the development of the Olympic Movement.])
#course(name: [Olympic Education (Bilingual)], id: [XS043008], semester: [2023–2024, Semester 2], credit: [2], ects: [3], hours: [36], content: [- Universal values of Olympic education and localization in China - International Olympic education concepts and organizations - Practical pathways - School physical education design - Youth sport club curriculum design], description: [This course examines Olympic education values, international Olympic education concepts and organizations, practical pathways, and their application in schools and youth sport clubs.])
#course(name: [Social Psychology in Recreational Sports], id: [XS043004], semester: [2024–2025, Semester 1 (credit recognition)], credit: [2], ects: [3], hours: [36], content: [- Foundations and development of social psychology in leisure - Research methods - Leisure experience, needs and motivation - Personality, attitudes and leisure identity - Individual differences in leisure behaviour], description: [This course introduces social psychological approaches to leisure and recreational sport, including research methods, motivation, personality, attitudes, identity and leisure behaviour.])
#course(name: [Education], id: [XS043005], semester: [2025–2026, Semester 1], credit: [2], ects: [3], hours: [36], content: [- Objects and research methods of education - Historical development - Education, individuals and society - Educational aims and school systems - Curriculum and teaching - School management], description: [This course introduces the research objects and methods of education together with its fundamental concepts, historical development, social relationships, school systems, curriculum, teaching and school management.])

= Fitness, Exercise and Applied Sport Science
#course(name: [Guide on Fitness Training], id: [XS043025], semester: [2024–2025, Semester 1 (credit recognition)], credit: [4], ects: [6], hours: [72], content: [- Health assessment - Scientific foundations of fitness exercise - Fitness assessment methods - Exercise and programme design - Guidance for different population groups - Cardiorespiratory, flexibility, muscular and balance training - Exercise-load control and safety], description: [This course develops systematic knowledge and practical skills for fitness training, assessment, programme design, guidance for different populations, load control and safe implementation.])
#course(name: [Resistance Exercise], id: [XS043023], semester: [2024–2025, Semester 1], credit: [2], ects: [3], hours: [36], content: [- Physiological foundations - Classification and functions of resistance training - Techniques and methods - Programme and plan design - Exercise instruction skills], description: [This course introduces the physiological foundations and methods of resistance exercise and develops competence in training-plan design and instruction.])

= Sport Practice, Instruction and Competition Organization
#course(name: [Swimming], id: [XS042013], semester: [2023–2024, Semester 1], credit: [4], ects: [6], hours: [72], content: [- Competitive and practical swimming techniques - Water self-rescue and aquatic safety - Breaststroke, backstroke and front crawl - Practical aquatic skills], description: [This course develops swimming techniques, water-safety knowledge, self-rescue and practical aquatic skills.])
#course(name: [Tennis], id: [XS042014], semester: [2023–2024, Semester 1], credit: [2], ects: [3], hours: [32], content: [- Fundamental tennis theory - Basic techniques and tactics - Competition rules - Competition organization and scheduling], description: [This course introduces tennis theory, techniques, tactics, competition rules and competition organization and scheduling.])
#course(name: [Badminton], id: [XS042015], semester: [2023–2024, Semester 1], credit: [2], ects: [3], hours: [32], content: [- Origins and development - Etiquette and competition rules - Fundamental techniques and tactics - Sport-for-all fitness guidance], description: [This course combines theoretical and practical study of badminton and supports participation and sport-for-all guidance.])
#course(name: [Athletics], id: [XS043009], semester: [2023–2024, Semester 2], credit: [2], ects: [3], hours: [36], content: [- Fundamental theories - Running, jumping and throwing techniques - Teaching theories and methods - Development of physical capacities], description: [This course introduces fundamental theories, techniques and teaching methods in athletics and develops basic instructional competence.])
#course(name: [Basketball], id: [XS043010], semester: [2024–2025, Semester 1 (credit recognition)], credit: [2], ects: [3], hours: [36], content: [- Fundamental techniques and tactics - Tactical combinations - Competition organization and scheduling - Basic officiating - Recreational sport application], description: [This course develops basketball techniques and tactics together with competition organization, scheduling, officiating and recreational-sport application.])
#course(name: [Table Tennis], id: [XS043012], semester: [2024–2025, Semester 1 (credit recognition)], credit: [2], ects: [3], hours: [36], content: [- Fundamental theories, techniques and tactics - Teaching theories and methods - Competition rules - Competition organization and scheduling - Basic officiating], description: [This course develops table-tennis theory and practical skills together with teaching, scheduling, officiating and competition-organization competence.])
#course(name: [Woodball], id: [XS043014], semester: [2024–2025, Semester 1], credit: [2], ects: [3], hours: [36], content: [- Culture, origin and development - Fundamental techniques - Competition rules - Community sport-for-all activities - Competition organization], description: [This course introduces woodball culture, techniques and rules and develops the ability to organize community activities and competitions.])
#course(name: [Hip Hop], id: [XS043018], semester: [2024–2025, Semester 1 (credit recognition)], credit: [2], ects: [3], hours: [36], content: [- Fundamental concepts and movement characteristics - Rhythm and techniques - Hip hop combinations - Cultural dimensions], description: [This course introduces hip hop concepts, movement characteristics, rhythm, techniques, combinations and cultural dimensions.])
#course(name: [Sport Massage], id: [XS043019], semester: [2024–2025, Semester 1 (credit recognition)], credit: [2], ects: [3], hours: [36], content: [- Historical development and concepts - Mechanisms of manual techniques - Fundamental massage techniques - Approaches to common sport injuries - Health-oriented massage], description: [This course introduces massage in sport and health contexts, including manual techniques, approaches to sport-related injuries and health-oriented procedures.])

= Major Specialization
#course(name: [Theory and Practice on Tennis I], id: [XS042017wq1], semester: [2023–2024, Semester 2], credit: [4], ects: [6], content: [- Tennis-specific theory and practice - Technical and tactical development - Tennis teaching and training - Competition rules and organization], description: [This is a completed semester-level component of the multi-semester tennis major specialization. The overall curriculum specialization extends across multiple semesters; this entry reports only the 4 CUPES credits evidenced for this completed component.])

= Supporting Business and Academic Skills
#course(name: [Innovation and Entrepreneurship Fundamentals], id: [XS041009], semester: [2024–2025, Semester 1 (credit recognition)], credit: [4], ects: [6], content: [- Innovation and entrepreneurial awareness - Entrepreneurial teams and opportunities - Business models - Business-plan preparation], description: [This course introduces innovation and entrepreneurship, including entrepreneurial teams and opportunities, business models and business-plan preparation. The credit value follows the student's recognized academic record.])
#course(name: [College Chinese], id: [XS041010], semester: [2024–2025, Semester 1 (credit recognition)], credit: [2], ects: [3], hours: [36], content: [- Reading and analysis - Language expression and writing - Humanities and cultural literacy - Written expression supporting academic study and thesis writing], description: [This course develops reading analysis and written expression. The curriculum states that these skills support professional study, thesis writing and communication of research outcomes.])

// ECTS-equivalent values in this application library use the applicant-selected calculation 1 CUPES credit = 1.5 ECTS.
// Grade information is intentionally omitted. Semester and credit values follow confirmed academic-record information where available.
